"use client";

import { useState } from "react";
import Link from "next/link";
import type { AgentRun } from "@/app/workspace";
import styles from "@/app/workspace.module.css";
import {
  evidenceFromRun,
  technicalStep,
} from "./presentation";

type Props = {
  run?: AgentRun;
  loading: boolean;
  open: boolean;
  onClose: () => void;
};

export function EvidenceRail({ run, loading, open, onClose }: Props) {
  const [technicalOpen, setTechnicalOpen] = useState(false);
  const evidence = evidenceFromRun(run);
  const hasRun = loading || Boolean(run);

  return (
    <aside
      id="evidence-drawer"
      className={`${styles.evidenceRail} ${
        open ? styles.evidenceDrawerOpen : ""
      }`}
      aria-label="Evidence trace"
    >
      <div className={styles.drawerHeader}>
        <strong>Evidence & audit</strong>
        <button type="button" onClick={onClose} aria-label="Close evidence">
          ×
        </button>
      </div>

      <section className={styles.panel}>
        <div className={styles.panelHead}>
          <h2 className={styles.panelTitle}>Evidence trace</h2>
          <span className={styles.panelNote}>
            {loading ? "running" : run ? "complete" : "waiting"}
          </span>
        </div>

        {!hasRun ? (
          <div className={styles.railIdle}>
            <div className={styles.railIdleIcon} aria-hidden="true">
              ⌕
            </div>
            Ask a question to see retrieved passages, dataset queries, and
            grounding notes.
          </div>
        ) : (
          <>
            <div className={styles.panelBody}>
              {loading && evidence.length === 0 ? (
                <div className={styles.thinking}>
                  <span className={styles.pulseDot} />
                  Planning and calling tools…
                </div>
              ) : evidence.length > 0 ? (
                <div className={styles.traceList}>
                  {evidence.map((item) => (
                    <article
                      className={`${styles.traceItem} ${
                        item.active ? styles.traceItemActive : ""
                      }`}
                      key={item.id}
                    >
                      <div className={styles.traceTop}>
                        <b>{item.label}</b>
                        <span className={styles.traceId}>{item.id}</span>
                      </div>
                      <p className={styles.traceText}>{item.detail}</p>
                      <div className={styles.traceChips}>
                        {item.chips.map((chip) => (
                          <span className={styles.traceChip} key={chip}>
                            {chip}
                          </span>
                        ))}
                      </div>
                    </article>
                  ))}
                </div>
              ) : (
                <p className={styles.directAnswer}>
                  No tools were needed for this answer.
                </p>
              )}
            </div>

            <div className={styles.viewToggle}>
              <button
                className={styles.toggleButton}
                type="button"
                aria-expanded={technicalOpen}
                onClick={() => setTechnicalOpen((current) => !current)}
              >
                <span
                  className={`${styles.toggleArrow} ${
                    technicalOpen ? styles.toggleArrowOpen : ""
                  }`}
                  aria-hidden="true"
                >
                  ▶
                </span>
                {technicalOpen
                  ? "Hide technical details"
                  : "Show technical details"}
              </button>
            </div>

            {technicalOpen ? (
              <div className={styles.technicalSection}>
                {run?.trace.map((step, index) => (
                  <div className={styles.technicalRow} key={`${step.tool}-${index}`}>
                    <span>{index + 1}</span>
                    <code>{technicalStep(step)}</code>
                  </div>
                ))}
              </div>
            ) : null}
          </>
        )}
      </section>

      <section className={styles.panel}>
        <div className={styles.panelHead}>
          <h2 className={styles.panelTitle}>Confidence</h2>
        </div>
        <div className={styles.pendingPanel}>
          <b>Backend support pending</b>
          <span>No confidence score is generated by the current API.</span>
        </div>
      </section>

      <section className={styles.panel}>
        <div className={styles.panelHead}>
          <h2 className={styles.panelTitle}>Audit info</h2>
        </div>
        <div className={styles.auditList}>
          <div className={styles.auditRow}>
            <span>Workspace</span>
            <b>ChiEAC</b>
          </div>
          <div className={styles.auditRow}>
            <span>Run mode</span>
            <b>Live</b>
          </div>
          <div className={styles.auditRow}>
            <span>Last answer</span>
            <b>
              {run?.completedAt
                ? run.completedAt.toLocaleTimeString([], {
                    hour: "2-digit",
                    minute: "2-digit",
                  })
                : "—"}
            </b>
          </div>
          <div className={styles.auditRow}>
            <span>Latency</span>
            <b>{run?.latency ? `${(run.latency / 1000).toFixed(2)}s` : "—"}</b>
          </div>
          <div className={styles.auditRow}>
            <span>System evaluation</span>
            <Link href="/dashboard">View dashboard →</Link>
          </div>
        </div>
      </section>

      {run && !loading ? (
        <section className={styles.panel}>
          <div className={styles.panelHead}>
            <h2 className={styles.panelTitle}>Sources used</h2>
            <span className={styles.panelNote}>{run.sources.length}</span>
          </div>
          <div className={styles.panelBody}>
            {run.sources.length > 0 ? (
              <div className={styles.usedSourceList}>
                {run.sources.map((source) => (
                  <div className={styles.usedSource} key={source.filename}>
                    <span>{source.type.toUpperCase()}</span>
                    <div>
                      <b>{source.filename}</b>
                      <small>
                        {source.passages} passage
                        {source.passages === 1 ? "" : "s"} retrieved
                      </small>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className={styles.directAnswer}>
                No documents used. This answer came from program data or
                conversation context.
              </p>
            )}
          </div>
        </section>
      ) : null}
    </aside>
  );
}
